// Ordered by hand rather than autogenerated: the reading order (overview →
// install → daily use → reference) does not match alphabetical file order, and
// an autogenerated sidebar would need a _category_.json in every docs subfolder.

const sidebars = {
  docs: [
    'README',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: ['getting-started/quick-start'],
    },
    {
      type: 'category',
      label: 'Usage',
      collapsed: false,
      items: ['usage/cli', 'usage/skills', 'configuration'],
    },
    'security',
    'troubleshooting',
    {
      type: 'category',
      label: 'Skills',
      items: ['skills/authoring'],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: ['advanced/cache', 'advanced/serve-mode', 'advanced/nono'],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing/development',
        'contributing/testing',
        'contributing/design',
        'contributing/echo-rest',
        'contributing/serve-spec',
      ],
    },
  ],
};

export default sidebars;
